linters:
  Indentation:
    width: 4

  PropertySortOrder:
    enabled: true
    order: ["content", "z-index", "overflow", "overflow-x", "overflow-y", "float", "clear", "table-layout", "border-collapse", "empty-cells", "box-sizing", "position", "top", "right", "bottom", "left", "width", "min-width", "max-width", "height", "min-height", "max-height", "display", "visibility", "margin", "margin-top", "margin-right", "margin-bottom", "margin-left", "padding", "padding-top", "padding-right", "padding-bottom", "padding-left", "border", "border-width", "border-style", "border-color", "border-radius", "border-top", "border-top-width", "border-top-style", "border-top-color", "border-right", "border-right-width", "border-right-style", "border-right-color", "border-bottom", "border-bottom-width", "border-bottom-style", "border-bottom-color", "border-left", "border-left-width", "border-left-style", "border-left-color", "border-top-left-radius", "border-top-right-radius", "border-bottom-right-radius", "border-bottom-left-radius", "white-space", "background", "background-color", "background-image", "background-repeat", "background-attachment", "background-position", "background-size", "opacity", "font", "font-family", "font-weight", "font-style", "font-variant", "font-size", "letter-spacing", "line-height", "list-style", "list-style-type", "list-style-position", "list-style-image", "outline", "outline-width", "outline-style", "outline-color", "text-align", "text-decoration", "text-indent", "text-transform", "color", "text-shadow", "animation", "transform", "transition", "box-shadow"]
    ignore_unspecified: true

  PropertySpelling:
    enabled: true
    extra_properties: ['*behavior']

  SelectorDepth:
    enabled: true
    max_depth: 6

  NestingDepth:
    enabled: true
    max_depth: 6
